version: '3.9'

services:

  db:
    image: postgres:16-bookworm
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cantina
      POSTGRES_USER: cantina
    networks:
      - local-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - local-network

volumes:
  pgdata:

networks:
  local-network:
    driver: bridge
