version: '3.9'

services:

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cantina
      POSTGRES_USER: cantina

volumes:
  pgdata:

networks:
  default:
    name: local-network
