version: '3.9'

services:

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cantina
      POSTGRES_USER: cantina
    networks:
      - local-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile2.local
    command: npm run start:debug
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/code
    networks:
      - local-network

volumes:
  pgdata:
  node_modules: 

networks:
  local-network:
    driver: bridge
