version: '3.8'

services:
  db:
    image: postgres:16
    networks:
      - app_network
    environment:
      POSTGRES_USER: cantina
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cantina
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10

  cantinabackend:
    image: h1bertobarbosa/cantina-backend:latest
    networks:
      - app_network
    environment:
      NODE_ENV: production
    deploy:
      replicas: 3
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

networks:
  app_network:
    driver: overlay

volumes:
  pg_data:
