version: '3.8'

services:
  db:
    image: postgres:16
    networks:
      - app_network
    environment:
      POSTGRES_USER: cantina
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cantina
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager # Banco rodando apenas no manager
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cantina'] # Ajustado para usuário correto
      interval: 10s # Aumentado para evitar sobrecarga no início
      timeout: 5s
      retries: 5

  cantinabackend:
    image: h1bertobarbosa/cantina-backend:latest
    networks:
      - app_network
    environment:
      NODE_ENV: production
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1 # Evita que todas as instâncias reiniciem ao mesmo tempo
        delay: 10s
    ports:
      - 3000:3000

networks:
  app_network:
    driver: overlay
    attachable: true

volumes:
  pg_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/swarm_pg_data
      o: bind
